# Generated by Django 3.1.3 on 2021-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('released_year', models.IntegerField(verbose_name='released year')),
                ('rating', models.CharField(max_length=255, verbose_name='rating')),
                ('movie_id', models.CharField(max_length=255, verbose_name='movie id')),
                ('genres', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
